version: '3.8'

services:
  nextcloud-db:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - /mnt/internal-hdd/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud_secure_root_2025
      - MYSQL_PASSWORD=nextcloud_secure_pass_2025
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud-net

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - 8083:80
    volumes:
      - /mnt/internal-hdd/nextcloud/data:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud_secure_pass_2025
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.1.176 heimdall
      - OVERWRITEPROTOCOL=http
    depends_on:
      - nextcloud-db
    networks:
      - nextcloud-net

networks:
  nextcloud-net:
    driver: bridge
